version: 1.0.{build}
platform:
  - x64

branches:
  only:
    - master

environment:
  matrix:
    - php_ver: "5.6.4"

install:
  -ps: Set-Service wuauserv -StartupType "Automatic"; Start-Service wuauserv
  - npm install npm@latest -g
  - cp .env.example .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - npm install

# Finish on first failed build
matrix:
  fast_finish: true

# Disable Visual Studio build and deploy
build: off
deploy: off

test_script:
  - vendor/bin/phpunit
  - npm --version
  - npm run production

cache:
  - node_modules
  - vendor

notifications:
  # Email
  - provider: Email
    to:
      - basri.official.acc@gmail.com
      - basri.basreen@gmail.com
    on_build_status_changed: true
